exclude = ["./tests"]

line-length = 150

[lint]
select = [
    "E",   # базовые ошибки pycodestyle
    "F",   # ошибки Pyflakes (неиспользуемые импорты, переменные и т.п.)
    "B",   # частые баги (flake8-bugbear)
]

# Игнорируем придирчивые правила
ignore = [
    "E501",  # длина строки (мы уже задали line-length)
]

# Не ругаться на underscore переменные
dummy-variable-rgx = "^_+$|^_.*"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
